version: "2"
services:
  profile:
    container_name: profile
    image: profile
    build: ./profile
    ports:
      - "8081:8081"
    depends_on:
      - profile_db
    links:
      - profile_db
  profile_db:
    image: profile:11
    container_name: profile_db
    ports:
      - "5432:5432"
    volumes:
      - /var/www/mangaladb/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=profile
