version: "3.5"
services:
  profile:
    container_name: profile
    image: profile
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - profiledb
    networks:
      - venusnet
  profiledb:
    image: postgres:11
    container_name: profiledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=profile
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - venusnet
networks:
  venusnet:
    driver: bridge
    name: venusnet

